site_name: Krembot wiki
pages:
    - Home: 'index.md'
    - Installation: 'Installation.md'
    - Getting Started: 'Getting_started.md'
    - API:     
        - 'API': 'API/API.md'
        - 'Battery and charge monitoring': 'API/Battery_and_charge_monitoring.md'
        - 'Bumpers': 'API/Bumpers.md'
        - 'Differential driving': 'API/Differential_driving.md'
        - 'Imu': 'API/Imu.md'
        - 'RGB ambient and proximity': 'API/RGB_ambient_and_proximity.md'
        - 'RGB leds': 'API/RGB_leds.md'
    - Demos:
        - 'Demos': 'Demos/Demos.md'
        - 'chameleon': 'Demos/chameleon.md'
        - 'Leds And Bumpers': 'Demos/ledsAndBumpers.md'
        - 'Publisher': 'Demos/Publisher.md'
        - 'Run Away By Bumpers': 'Demos/RunAwayByBumpers.md'
        - 'Stop By Wall': 'Demos/StopByWall.md'
        - 'Subscriber': 'Demos/Subscriber.md'
    - Problem Solving: 'Problem_Solving.md'

theme: readthedocs
